/**
 * QA Simulator — report generator.
 *
 * Produces both a JSON report and a Markdown report from QAReport data.
 * Neither function writes files; the runner decides where to write.
 */

import type { QAReport, ScenarioResult } from "./types.js";

// ---------------------------------------------------------------------------
// JSON
// ---------------------------------------------------------------------------

/** Serialise the full report to a pretty-printed JSON string. */
export function buildJsonReport(report: QAReport): string {
  return JSON.stringify(report, null, 2);
}

// ---------------------------------------------------------------------------
// Markdown
// ---------------------------------------------------------------------------

function badge(n: number, label: string): string {
  return `**${n}** ${label}`;
}

function statusEmoji(status: ScenarioResult["status"]): string {
  switch (status) {
    case "passed":
      return "PASS";
    case "failed":
      return "FAIL";
    case "skipped":
      return "SKIP";
    case "dry-run":
      return "DRY";
  }
}

/** Produce a Markdown report string from the QAReport. */
export function buildMarkdownReport(report: QAReport): string {
  const { summary, results, missingEndpoints, blockers } = report;

  const lines: string[] = [];

  lines.push(`# Unboks QA Agent Report`);
  lines.push(``);
  lines.push(`| Field | Value |`);
  lines.push(`|---|---|`);
  lines.push(`| Date | ${summary.date} |`);
  lines.push(`| Environment | ${summary.environment} |`);
  lines.push(`| Tenant | ${summary.tenant} |`);
  lines.push(`| QA customer email | ${summary.qaCustomerEmail} |`);
  lines.push(`| Mode | ${summary.mode} |`);
  lines.push(`| Total tests | ${summary.total} |`);
  lines.push(`| Passed | ${summary.passed} |`);
  lines.push(`| Failed | ${summary.failed} |`);
  lines.push(`| Skipped / dry-run | ${summary.skipped + summary.dryRun} |`);
  lines.push(``);

  // Severity breakdown
  lines.push(`## Severity breakdown`);
  lines.push(``);
  lines.push(`| Severity | Passed | Failed |`);
  lines.push(`|---|---|---|`);
  for (const sev of ["critical", "high", "medium", "low"] as const) {
    const s = summary.bySeverity[sev];
    lines.push(`| ${sev} | ${s.passed} | ${s.failed} |`);
  }
  lines.push(``);

  // Category breakdown
  lines.push(`## Category breakdown`);
  lines.push(``);
  lines.push(`| Category | Passed | Failed | Skipped |`);
  lines.push(`|---|---|---|---|`);
  for (const [cat, counts] of Object.entries(summary.byCategory)) {
    lines.push(`| ${cat} | ${counts.passed} | ${counts.failed} | ${counts.skipped} |`);
  }
  lines.push(``);

  // Failed scenarios
  const failed = results.filter((r) => r.status === "failed");
  if (failed.length > 0) {
    lines.push(`## Failed tests`);
    lines.push(``);
    for (const r of failed) {
      lines.push(`### ${r.testId} (${r.severity})`);
      lines.push(``);
      if (r.error) lines.push(`**Runner error:** ${r.error}`);
      const failedChecks = r.checks.filter((c) => c.status === "fail");
      if (failedChecks.length > 0) {
        lines.push(`**Failed checks:**`);
        for (const c of failedChecks) {
          lines.push(`- ${c.name}${c.detail ? `: ${c.detail}` : ""}`);
        }
      }
      lines.push(`**Duration:** ${r.durationMs}ms`);
      lines.push(``);
    }
  }

  // Full results table
  lines.push(`## All results`);
  lines.push(``);
  lines.push(`| Test ID | Category | Severity | Status | Duration |`);
  lines.push(`|---|---|---|---|---|`);
  for (const r of results) {
    lines.push(
      `| ${r.testId} | ${r.category} | ${r.severity} | ${statusEmoji(r.status)} | ${r.durationMs}ms |`,
    );
  }
  lines.push(``);

  // Passed areas summary
  const passedCats = Object.entries(summary.byCategory)
    .filter(([, v]) => v.passed > 0)
    .map(([k]) => k);
  if (passedCats.length > 0) {
    lines.push(`## Passed areas`);
    lines.push(``);
    for (const cat of passedCats) {
      lines.push(`- ${cat}`);
    }
    lines.push(``);
  }

  // Missing endpoints
  if (missingEndpoints.length > 0) {
    lines.push(`## Missing / unverifiable endpoints`);
    lines.push(``);
    for (const ep of missingEndpoints) {
      lines.push(`- \`${ep}\``);
    }
    lines.push(``);
  }

  // Blockers
  if (blockers.length > 0) {
    lines.push(`## Blockers`);
    lines.push(``);
    for (const b of blockers) {
      lines.push(`- ${b}`);
    }
    lines.push(``);
  }

  lines.push(`---`);
  lines.push(`_Generated by scripts/src/qa/runner.ts — ${badge(summary.total, "scenarios")} evaluated_`);

  return lines.join("\n");
}
