import type { MermaidReservationDetail } from "@/lib/api";

export const mermaidReceiptFixture: MermaidReservationDetail = {
  publicId: "synthetic-reservation",
  conversationId: "synthetic-guest-contact",
  customerName: "Alex Example",
  language: "en",
  tripDate: "2026-09-12",
  adults: 2,
  children: 1,
  infants: 1,
  pickupPreference: "pickup_requested",
  pickupLocation: "Example hotel lobby",
  dietaryRequirements: "One vegetarian meal",
  specialRequests: "Please keep the family together.",
  catalogVersion: "synthetic-catalog-v1",
  currency: "USD",
  total: 375,
  items: [
    {
      key: "adult",
      label: "Adult",
      quantity: 2,
      unit_amount: 150,
      line_total: 300,
    },
    {
      key: "child",
      label: "Child (4-12)",
      quantity: 1,
      unit_amount: 75,
      line_total: 75,
    },
    {
      key: "infant",
      label: "Infant (0-3)",
      quantity: 1,
      unit_amount: 0,
      line_total: 0,
    },
  ],
  state: "booked",
  stage: "booked",
  availabilitySource: "demo_assumed",
  bookingCode: "DEMO-PRINT-001",
  paymentReference: "SIMULATED-PAYMENT-001",
  receiptPublicId: "synthetic-receipt-001",
  humanTakeover: false,
  revision: 7,
  createdAt: "2026-09-03T12:00:00Z",
  updatedAt: "2026-09-03T13:00:00Z",
  primaryAction: {
    id: "view_receipt",
    label: "View receipt evidence",
    href: "/reservations/synthetic-reservation",
  },
  demo: true,
  documents: [
    {
      public_id: "synthetic-receipt-001",
      kind: "receipt",
      filename: "receipt.pdf",
      sha256: "synthetic",
      created_at: "2026-09-03T13:00:00Z",
    },
  ],
  events: [],
  conversation: [
    {
      role: "user",
      text: "Private conversation text must not appear on paper",
      created_at: "2026-09-03T12:00:00Z",
    },
  ],
};
